### ISSUE TITLE
(ВОЗМОЖНО ГЛАВНЫЙ ОБОСРАМС)There are too many mandatory overmap specials (83 > 72). Some of them may not be placed. 

### ISSUE THREAD

**Issue by Adevald** [Adevald/Cataclysm_DDA_Mod_Content_Extension#10]
DEBUG    : There are too many mandatory overmap specials (83 > 72). Some of them may not be placed.
 
 FUNCTION : void overmap_specials::check_consistency()
 FILE     : src/overmap.cpp
 LINE     : 339

**Comment by Adevald** [comment]
Слишком много спавнящихся локаций, поэтому всё отлетает нахуй. Предлагаю перебрать моды на постройки, поудалять мусор, или вообще вырубить.

**Comment by SomeDeadGuy** [comment]
Параметр Occurences в overmap specials файле в модах уменьшай в соответствии с логикой.

**Comment by Adevald** [comment]
@SomeDeadGuy я до сих пор не вдуплил за что этот параметр отвечает.

**Comment by SomeDeadGuy** [comment]
За шанс спавна локации на овермапе, я так считаю. Мол их может даже несколько заспавниться на одной. Всяким чудным локациям, которые маловероятны стоит уменьшить этот параметр сильно, а другим, которые обычные, и во время какаклизмы могли бы быть где угодно и встречатся часто всё равно можно уменьшить этот параметр, но уже на чуть-чуть.
