### ISSUE TITLE
No item tilesets in Vampiric Stuff (Нет наборов плиток в Vampiric Stuff)

### ISSUE THREAD

**Issue by ghost** [Adevald/Cataclysm_DDA_Mod_Content_Extension#11]
I am sorry for bothering you at this moment but I see that there is no item tileset included in the mod I've said earlier.
Прошу прощения, что беспокою вас в данный момент, но я вижу, что в моде, о котором я говорил ранее, нет набора плиток предметов.

(I appreciate your help for translating the mod to Russian BTW :+1: )
(Спасибо за помощь в переводе мода на русский Кстатиc :+1:  )

**Comment by Adevald** [comment]
@Axema  Я его недавно обновил, это ты же его делаешь, да? Мне нравится очень.
Im update the mod recently. You are a developer of Vampire, yes? I like it. 
Do you know Russian?

**Comment by SomeDeadGuy** [comment]
Nah, he is not. :)
Он ещё Secronom запилил, даже тайлы нарисовал к моду сам https://github.com/Axema/Secronom-Zombies

**Comment by ghost** [comment]
> @Axema Я его недавно обновил, это ты же его делаешь, да? Мне нравится очень.
> Im update the mod recently. You are a developer of Vampire, yes? I like it.
> Do you know Russian?

Oh, I am.  Thanks!
О, я Спасибо :smile:

I don't know Russian, but its okay. Google translate helps me with your language
Я не знаю русский, но все в порядке. Google переводчик помогает мне с вашим языком :+1:

**Comment by Adevald** [comment]
@Axema You may not translate on English, because im understand it well. But maybe not enough to write proper sentences :D And whats about completeness of your 2 mods, how often you'll be update it? Because now im just dont know how to autimate translition and now i need to move every strig one by one into the json files, every new update. As you can see, thats not enough easy.

@SomeDeadGuy  А он мощный чувак. Я тоже хочу моды делать, но пока меня стопорнуло то, что скрипты свои придётся писать на C++ и непосредственно в игру вшивать через мастер гит репо.

**Comment by ghost** [comment]
Well, about the two mods that I have, the secronom mod is pretty much stable now but the vampiric stuff mod... It is not.
Sorry about the intensive updates I'm doing for that mod because it is practically WIP, for 6 months! Maybe try to update your repository after a week, just to prevent yourself from consuming your time everyday :smiley:

**Comment by Adevald** [comment]
@Axema Im not sure how to github works... Maybe here can be some useful utilites for fast translition update... And i think i add secronom for modpack :^)

**Comment by ghost** [comment]
Good luck about it then :wink:

**Comment by Adevald** [comment]
@Axema I have some idea. What if create new branch on your Vampire mod repo, and make all translition there? How to changes of master branch will affect on rus branch?

**Comment by ghost** [comment]
> @Axema I have some idea. What if create new branch on your Vampire mod repo, and make all translition there? How to changes of master branch will affect on rus branch?

I don't know how github works, but I'll try it out :wink:

**Comment by Adevald** [comment]
@Axema Oh, Thanks! You need just add me ti the contributors, and in settings -> Branches -> Branch protection rule requires pull request before merging and Require review from Code Owners.
It protect your code, just in case. And then just go to branch menu and create master_rus branch. The rest of the work is on me.

**Comment by ghost** [comment]
I did what you told me, thanks :)

**Comment by Adevald** [comment]
@Axema I think there is some reason to check how it will work. Now just approve pull request, and when you change some in file (like some parameters on v_books.json , and description, just for check), i tried to move new changes to master_rus. In theory its simple.
