### ISSUE TITLE
Many bugs on the current version

### ISSUE THREAD

**Issue by lex1975** [Adevald/Cataclysm_DDA_Mod_Content_Extension#16]
Many bugs on the current version
Unfortunately, the assembly is not working on the next version of CDDA
К сожалению, сборка нерабочая на ближайшей версии каты
https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b9044
Windows 7 x32 Corporate Edition (cataclysmdda-0.D-Windows_x32-Tiles-9044.zip)

К автору сборки модов большая просьба.
Пожалуйста, вместе со сборкой выкладывайте ссылку на версию каты с которой ваша сборка работает.
To the author of the assembly mods a big request.
Please, together with the assembly, post a link to the version of the CDDA with which your assembly works.

**Comment by lex1975** [comment]
Пробую на последней стабилке
cataclysmdda-0.D-8574-Win-Tiles
Но ошибки всё те же.

**Comment by lex1975** [comment]
Короче, если тебе надо, вот багрепорты на последнюю эксперименталку.
Я не догнал сначала, после нажатия пробелов игра запускается. Дальше не тестил пока.
На последней эксперименталке меньше ошибок.
cataclysmdda-0.D-Windows_x32-Tiles-9859
(отображается как 0.D-9090. Так и не понял что за чехарда с версиями - у архива одна версия, а в игре отображается другая.)
Оказывается, при показе ошибки надо жать пробел и можно играть.

По-моему, у меня устаревший браузер и сюда файлы не прикрепляются.
Вот ссылка на багрепорты
https://2ch.hk/vg/src/31834990/15729782805780.jpg

**Comment by Adevald** [comment]
У тебя игра падает, когда загрузка всех модов происхоит? Если да - то пробуй ту версию которая указана в группе. Если нет. То это не сильно критичные вещи, и без них играть можно, но я попозже исправлю.

**Comment by lex1975** [comment]
Нет, не падает. Спасибо за сборку. Попробую играть.
Пожалуйста, если не трудно, размещай у себя ссылку на версию каты под твою текущую сборку. Из-за чехарды с версиями (версия архива не соответствует версии каты отображаемой в игре) сложно отыскать нужную версию на гитхабе. Кроме того, на гитхабе нет поиска нормального.

**Comment by Adevald** [comment]
Все ошибки я пофиксил, хотя всё еще есть проблемы с некоторыми сценариями, но это я пока вообще хуй знает как решать. Попозже разбираться буду
